version: '3'

services:
  dev:
    build: .
    image: parceldock
    ports:
      - "1234:1234"
    volumes:
      - .:/app/
      - ./dist/:/app/dist/
#  wolf:
#    image: wolf
#    build: wolf/
#    depends_on:
#      - mongo
#      - leo
#    networks:
#      - cb
#      - back
    # volumes:
      # - ./wolf:/wolf/
#  mongo:
#    image: mongo
#    networks:
#      - back
#networks:
#  cb:
#  back:
