version: '3'

services:
  web:
    build: .
    image: parceldock
    ports:
      - '1234:1234'
      - '1235:1235'
    volumes:
      - .:/app/
      - ./dist/:/app/dist/
    command: npm run build
  api:
    image: api
    build:
      context: .
      dockerfile: leo/Dockerfile
    volumes:
      - .:/app
      # - ./dist:/app/dist
      # - ./pdf:/app/pdf
    depends_on:
      - mongo
    networks:
      - back

  mongo:
    image: mongo
    networks:
      - back

networks:
  back:
