version: '3'

services:
  leo:
    build: .
    image: leo
    ports:
      - "7777:7777"
    networks:
      - cb
    volumes:
      - ./web:/leo/:ro
  wolf:
    image: wolf
    build: wolf/
    depends_on:
      - mongo
      - leo
    networks:
      - cb
      - back
#    volumes:
      # - ./wolf:/wolf/
      #- wolf
  mongo:
    image: mongo
    networks:
      - back

volumes:
  web:
#  wolf:

networks:
  cb:
  back:
