version: '3'

services:
  dev:
    build: .
    image: parceldock
    ports:
      - "1234:1234"
    volumes:
      - .:/app/
      - ./dist/:/app/dist/
  wolf:
    image: wolf
    build: wolf/
    ports:
     - "8000:8000"
    volumes:
      - ./wolf:/wolf
      - ./dist:/wolf/dist
      - ./web/pdf:/wolf/web/pdf
#    depends_on:
#      - mongo
#      - leo
#    networks:
#      - cb
#      - back
    # volumes:
      # - ./wolf:/wolf/
#  mongo:
#    image: mongo
#    networks:
#      - back
#networks:
#  cb:
#  back:
