version: '3'

services:
  dev:
    build: .
    image: parceldock
    ports:
      - '1234:1234'
      - '1235:1235'
    volumes:
      - .:/app/
      - ./dist/:/app/dist/
  wolf:
    image: wolf
    build: wolf/
    volumes:
      - ./leo:/wolf
      - ./dist:/wolf/dist
      - ./pdf:/wolf/pdf
    depends_on:
      - mongo
    networks:
      - back

  mongo:
    image: mongo
    networks:
      - back

networks:
  back:
