version: '3'

services:
  wolf:
    networks:
      - web:
    labels:
      - 'traefik.HTTP.Routers.leo.Rule=Host(`leo.quaternion.media`)'
      - 'traefik.HTTP.Routers.leos.Rule=Host(`leo.quaternion.media`)'
      - 'traefik.HTTP.Routers.leos.tls=true'
      - 'traefik.HTTP.Routers.leo.middlewares=file.redirect'
      - 'traefik.docker.network=web'
    expose:
      - "80"
networks:
  web:
    external:
      name: web
